Development
catenax-ng/k8s-helm-example pull request #5
Opened 2022-04-05 09:53 UTC by sTb1337

2022-04-05 10:38 UTC, Siegfriedk requested changes
Pls see comments

2022-04-05 10:38 UTC, Siegfriedk commented on README.md
> +### Folder Structure
Please add new lines after headers / sections

2022-04-05 10:38 UTC, Siegfriedk commented on README.md
> +2. Copy [static HTML](html/) content into nginx [htdocs](https://www.nginx.com/resources/wiki/start/topics/examples/full/) folder.
When you use 1., 1., 1. instead of 1., 2., 3. you can add and change the list and markdown will update the numerics automatically.

This is easier to update the list if you don't have an ide which does that automatic for you.

2022-04-05 10:38 UTC, Siegfriedk commented on docker/default.conf
> +    #access_log  /var/log/nginx/host.access.log  main;
Pls remove commeted out statements.

2022-04-05 10:38 UTC, Siegfriedk commented on helm/cx-argo-cd-example/Chart.yaml
>  name: cx-argo-cd-example
This repo is not an argo cd example because it doesn't matter what or who its deploying it.

The focus of this repo is helm. k8s-helm-example would be much better fit than *argo-cd*

2022-04-05 10:38 UTC, Siegfriedk commented on helm/cx-argo-cd-example/templates/deployment.yaml
> +              port: {{ .Values.livenessProbe.port }}
You mentioned in the last PR that we should not remove functionanlity which was given to us.

The thing with a probe is, that you do not change it. At least not the path and the port. You might want to update the seconds if your setup is more complex but not path and port.

I would still either remove it completly or at least remove path and port.

2022-04-05 10:38 UTC, Siegfriedk commented on helm/cx-argo-cd-example/values-int.yaml
> +  #    hosts:
Pls remove commented out code.

You mentioned in the other PR that you need this for tls but commented out code is not used.

2022-04-05 10:38 UTC, Siegfriedk commented on helm/cx-argo-cd-example/values.yaml
> +autoscaling:
autoscaling is not used on a vertical level.

I'm also not able to find minReplicas or maxReplaces used in the code. Where is this used?

2022-04-05 10:38 UTC, Siegfriedk commented on helm/cx-argo-cd-example/values.yaml
> -  #  - secretName: chart-example-tls
Here as well, pls remove unused comments. If you want to keep it to highlight the location for ricos approach, pls add a hint comment.

2022-04-05 12:29 UTC, sTb1337 commented on helm/cx-argo-cd-example/templates/deployment.yaml
> +              port: {{ .Values.livenessProbe.port }}
It is highly unlikely that the path + port is the same for other applications, so better keep it configurable.

2022-04-05 12:55 UTC, Siegfriedk commented on helm/cx-argo-cd-example/templates/deployment.yaml
> +              port: {{ .Values.livenessProbe.port }}
thats actually not the point; The helm chart you provide as an example will not be used by replacing the image but as a template;

the path and port will never change in their helm charts; Its also very realistic that they will add additional containers and therefore have more than one probe.

2022-04-06 08:45 UTC, Siegfriedk approved these changes

2022-04-06 09:16 UTC, merged